# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=64, null=True)),
                ('parent_ids', models.CharField(blank=True, max_length=2000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sort', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('create_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('del_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'village',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='bureauareas',
            name='pid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='village',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BureauAreas', to_field='pid'),
        ),
    ]
